name: steam_market
version: "1.0.0"
config-version: 2

profile: steam_market

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  steam_market:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
