apiVersion: 1

datasources:
  - name: SteamMarketMarts
    uid: steammarketmarts
    type: postgres
    access: proxy
    url: postgres-marts:5432
    database: marts
    user: marts
    isDefault: true
    editable: false
    secureJsonData:
      password: marts
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
